import { Router } from "express";
import isIdExistMW from "../middlewares/isIdExist";
import UserController from "../controllers/user.controller";
import upload from "../config/multer.config";
// import { updateUser } from "../services/user.service";
const path = "/user";
const pathWithId = "/user/:id";
const pathWithIdAndCart = "/user/:id/cart";
const pathWithIdAndWishlist = "/user/:id/wishlist";
const pathWithIdAndRate = "/user/:id/rate";
const pathWithIdAndOrder = "/user/:id/order";
const router: Router = Router();
router.get(path, UserController.getUsers);
router.use(pathWithId, isIdExistMW);
router.get(pathWithIdAndCart, UserController.getUserCart);
router.get(pathWithIdAndWishlist, UserController.getUserWishlist);
router.get(pathWithIdAndRate, UserController.getUserRate);
router.get(pathWithIdAndOrder, UserController.getUserOrder);
router.get(pathWithId, UserController.getUser);
router.delete(pathWithId, UserController.deleteUser);
router.use(pathWithId, upload.single("image"));
router.patch(pathWithId, UserController.updateUser);
export default router;
