import { Router } from "express";
import loginRoute from "./routes/login.route";
import cartRoute from "./routes/cart.route";
import categoryRoute from "./routes/category.route";
import productRoute from "./routes/product.route";
import profileRoute from "./routes/profile.route";
import signUpRoute from "./routes/sign-up.route";
import subcategoryRoute from "./routes/subcategory.route";
import userRoute from "./routes/user.route";
import rateRoute from "./routes/rate.route";
import wishlistRoute from "./routes/wishlist.route";
import orderRoute from "./routes/order.route";
import authMW from "./middlewares/verifyToken";
const app: Router = Router();
app.use(loginRoute);
app.use(signUpRoute);
app.use(authMW);
app.use(profileRoute);
app.use(userRoute);
app.use(productRoute);
app.use(subcategoryRoute);
app.use(categoryRoute);
app.use(cartRoute);
app.use(wishlistRoute);
app.use(rateRoute);
app.use(orderRoute)
export default app;
